### PR TITLE
#1343 Including video on the Engine product page

### PR DESCRIPTION
**Pull request by znegrin**
This PR is related to the backlog issue [#1343](https://github.com/src-d/backlog/issues/1343).

More information available on the document: [Landing Quick fixes & improvements](https://docs.google.com/document/d/1rCasMWwPL-VosmWCd98cXdZsQnBVbVjsuYdQvCbjO9c/edit#)

Added a responsive video and title on the Engine page as requested. Notice that the actual thumbnail differs from the desired one, but it should be changed on the YouTube video itself.

image

Signed-off-by: znegrin <zurinegrin@gmail.com>

### CODE REVIEW

**Comment by dpordomingo** [comment]
@ricardobaeta ready to be validated at staging
https://landing-staging.srcd.run/engine/

**Comment by znegrin** [comment]
@marnovo @ricardobaeta 

I still think that the problem is more on the video cover itself, and that it should be the purple introduction as on the UI Pattern Library. Also I made a test to see how it looks inside a white card:

image

Maybe changing the cover to this one makes it no necessary:

image

What do you think? Let me know and I will update it.

Thanks.

**Comment by ricardobaeta** [comment]
Hi @znegrin !

I like the solution for the card approach that Marcelo suggested, and changing the video cover as you suggest as well. What do you think @marnovo ?

**Comment by marnovo** [comment]
@znegrin @ricardobaeta pardon my ignorance but if it's possible to change the video cover (devrel can do that as long as we specify what we need), that works.

As for the white card around it (or other artifact that helps separate elements), remember that for the sake of consistency it should be the same or similar to [our solution for the UI image](https://github.com/src-d/landing/pull/353).

**Comment by znegrin** [comment]
@marnovo @ricardobaeta I just updated the PR adding it inside a card ([the exact same as the product UI](https://github.com/src-d/landing/pull/353)):

image

**Comment by ricardobaeta** [comment]
@dpordomingo Yes, I am :)

**Comment by dpordomingo** [comment]
merging into `src-d:new-engine-product-page`, that will be merged with the rest of the current improvements for engine site at once by https://github.com/src-d/landing/pull/356

**Pull request merged**
