### PR TITLE
Update Team page

### PR DESCRIPTION
**Pull request by estherrgarcia**
Signed-off-by: Esther García <esther@sourced.tech>

### CODE REVIEW

**Comment by vcoisne** [comment]
@estherrgarcia @znegrin for the new version of the website we have decided to only keep Management as this going to be easier to maintain up to date.

**Comment by vcoisne** [comment]
That being said we should include a team photo

**Comment by dpordomingo** [comment]
@vcoisne can I understand that we should keep updating team page until we have the new one?
or should we just leave it outdated till the new team page is deployed?

**Comment by estherrgarcia** [comment]
I would like to keep it updated. David was teaching me yesterday some stuff and it's a way to practice and learn.

**Pull request merged**
