### PR TITLE
New homepage on the website

### PR DESCRIPTION
**Pull request by znegrin**
Hi @vcoisne,

Here is the new index referred to the issue [#1404](https://github.com/src-d/backlog/issues/1404) on the backlog: [Website revamp on communication & structure w/ new pages](https://github.com/src-d/backlog/issues/1404). It adds changes on the source{d} homepage. 

Notice that the header navigation and the footer will be changed in a separate PR. It is also missing some images and the main header graphic once @vcoisne and @ricardobaeta decide on it.

Here is a screenshot of the full page:

image

Please let me know if everything is ok.

Thank you!

### CODE REVIEW

**Comment by vcoisne** [comment]
Thank you @znegrin we're getting there. 

1. For the visual next to the timeline you should already the image dimensions and positioning. It would be great if you already get that covered on code so that we can just replacing when @ricardobaeta is done (in 1 hour or so). 

2. Can we add the placeholder images from https://github.com/src-d/backlog/issues/1404 on the homepage as well for each tabs. 

3. Not sure why this header now says visual should be "Any Hosting Environments"

homepage

**Comment by vcoisne** [comment]
One last thing sorry! The 4 use case title are as follow:

- IT Modernization & Application Portfolio Management

- DevOps & Cloud Native adoption

- Engineering effectiveness & efficiency 

- Talent Assessment and Management

**Comment by znegrin** [comment]
Hi @vcoisne,

I added all the images and changes so now this should be ready and updated.

Thank you!

**Comment by vcoisne** [comment]
@znegrin thanks the sooner we can ship it the better. Looks like this branch has conflicts that must be resolved before we merge. Btw do you have rights to merge yourself?

**Comment by znegrin** [comment]
> @znegrin thanks the sooner we can ship it the better. Looks like this branch has conflicts that must be resolved before we merge. Btw do you have rights to merge yourself?

Hi @vcoisne,

I just fixed the merge and it seems it doesn't have conflicts anymore. I haven't done the merge in the past, so I guess that someone has to check everything and publish once ready.

Thanks

**Comment by dpordomingo** [comment]
Changing the target branch to be `ee-candidate` instead of `master`

**Comment by dpordomingo** [comment]
ready at staging:
https://landing-staging.srcd.run/

any review should be provided at candidate PR: https://github.com/src-d/landing/pull/390
(not here)

**Pull request merged**
