### PR TITLE
Add configurable prefix for api

### LINKED ISSUE #70: API should be capable to receive a configurable prefix
So that it can answer to `/<prefix>/repositories` if needed instead of rewriting the url path

### PR DESCRIPTION
**Pull request by Serabe**
Fixes #70 

Needs #73

### CODE REVIEW

**Comment by erizocosmico** [comment]
Why do we need this prefix? The caddy proxies the `/api` to `/`, so the route will be incorrect

**Comment by Serabe** [comment]
Because the caddy will be gone and we cannot have the `without api` rule in the new infra.

**Comment by dpordomingo** [comment]
can it be merged then @erizocosmico ?

**Comment by erizocosmico** [comment]
Yup

**Pull request merged**
