### PR TITLE
#1342 Adding Engine UI block on product page

### PR DESCRIPTION
**Pull request by znegrin**
This PR is related to the backlog issue [#1342](https://github.com/src-d/backlog/issues/1342).

More information available on the document: [Landing Quick fixes & improvements](https://docs.google.com/document/d/1rCasMWwPL-VosmWCd98cXdZsQnBVbVjsuYdQvCbjO9c/edit#)

Added a responsive image with the Engine UI with the reference text.

image

Signed-off-by: znegrin <zurinegrin@gmail.com>

### CODE REVIEW

**Comment by dpordomingo** [comment]
@ricardobaeta ready to be validated at staging
https://landing-staging.srcd.run/engine/

**Comment by ricardobaeta** [comment]
Hi @znegrin ! David has a good point here. I was thinking about the experience that google maps provide on mobile, and found this project, [magnifik](https://github.com/mobify/magnifik), that enables us to Zoom & Pan on any given image on mobile. I think there's so much we can do about this UI block given its complexity. Do you feel comfortable giving it a try?

**Comment by znegrin** [comment]
Hi @ricardobaeta,

I was thinking on making the image clickable so the user can see it full size and zoom it. 

I was testing the project you shared on my mobile devices and it seems a bit limited and confusing in terms of zooming to see the full image and then zoom to the desired parts, as you never see the full width image.

In this case I think it would be better an approach more similar to most mobile apps, where the images are clickable, then it takes the full width and you can zoom it as you want to see the details and then you can close it back. Something similar to Twitter or Facebook for example.

Did I explain myself right? If not I can make a mockup.

What do you think?

**Comment by ricardobaeta** [comment]
Hi @znegrin ! Seems fine to me! As long as you can Zoom & Pan like google maps, it's good. Please go ahead and provide the solution and update the PR!

**Comment by dpordomingo** [comment]
clickable image LGTM, but I'd suggest also do:
- an "optimized" image for mobile: maybe reducing or hiding the left collapsible aside, and reducing the complexity of the UI (using the chrome inspector to remove too much noisy items, increasing some fonts...)
- add a zoom icon to let the user know that the image is "zoomable"
- the "zoomed" version will be the real one; the "optimized" version is only shown as a call to action

:point_down: Here is an example of how it would look like with "optimized" version and "zoom icon":
gitbase

:point_down: Compared with current status:
image

:point_down: And here is the "optimized image" I used.
I'm sure you can enhance it way more :wink: 
gitbase-original

**Comment by ricardobaeta** [comment]
Thanks @marnovo and @dpordomingo !

@znegrin please move forward on this one too, thanks!

**Comment by znegrin** [comment]
Hi @marnovo @ricardobaeta 

I just pushed a change on the image to approach the "zoom" + card idea:

image

**Comment by ricardobaeta** [comment]
@dpordomingo Yes, I am! We just need to tackle https://github.com/src-d/landing/pull/354 for a bulk merge of the entire Engine page. I prefer to do this Engine's PR's all at once to have a brand new entire page.

**Comment by dpordomingo** [comment]
merging into `src-d:new-engine-product-page`, that will be merged with the rest of the current improvements for engine site at once by https://github.com/src-d/landing/pull/356

**Pull request merged**
