### PR TITLE
New Engineering Effectiveness & Efficiency page

### PR DESCRIPTION
**Pull request by znegrin**
As requested on the issue [#1404](https://github.com/src-d/backlog/issues/1404) of the Backlog, I added a page for the Engineering Effectiveness & Efficiency solution.

Please notice that it is still missing the images.

image

### CODE REVIEW

**Comment by dpordomingo** [comment]
already at staging:
https://landing-staging.srcd.run/solutions/engineering-effectiveness-efficiency/

there are some missing images that should be added before merging

**Comment by znegrin** [comment]
I added the three images of this page.

Maybe we can rethink about the layout, as with the images it has a lot of white space. I was thinking of putting below the intro text and the image the examples in two columns and then the buttons. What do you think @vcoisne?

image

**Comment by vcoisne** [comment]
yes @znegrin good idea. Can you try 2 columns?

**Comment by znegrin** [comment]
I fixed the merge and reorganised the layout. Now this page should be completely ready.

image

**Comment by znegrin** [comment]
> sorry @znegrin; we need your super powers solving conflicts 👯‍♂

Fixed 👍

**Pull request merged**
