### PR TITLE
Enhance slack form error message

### PR DESCRIPTION
**Pull request by dpordomingo**
Fixes https://github.com/src-d/backlog/issues/967

You will find below these lines screenshots of all defined states (`initial`, `success`), in desktop and mobile version, for the hero and footer slack forms.
The `onError` state screenshots are given by https://github.com/src-d/landing/pull/155#issuecomment-327240838 as requested by https://github.com/src-d/landing/pull/155#issuecomment-327022068 

### desktop
landing-slack-desktop

### iPhone 6 Plus
(no change due to resolution)

### desktop
image
image
image

### iPhone 6 Plus
landing-slack-iphone

/cc @marnovo

### CODE REVIEW

**Comment by dpordomingo** [comment]
If it is removed from the error message, the user will have no option to resend the form or to fix any typo that could have caused the error.
Before removing the send button we should ensure that resending the email has no sense at all with our current backend.

Removing the button on success is possible but would leave the horizontal form in a non symmetrical view when accessed via desktop; if you like it without the send button when success, just confirm me and I'll do so.

**Comment by ricardobaeta** [comment]
@dpordomingo 

> If it is removed from the error message, the user will have no option to resend the form or to fix any typo that could have caused the error.

I thought that the error specific message happens when there's nothing wrong with user input, but rather on our side, therefore, having the button - yet inactive - doesn't add any value.

> Before removing the send button we should ensure that resending the email has no sense at all with our current backend.

Could you explain please?

> Removing the button on success is possible but would leave the horizontal form in a non symmetrical view when accessed via desktop; if you like it without the send button when success, just confirm me and I'll do so.

On success the feedback typography block could be placed where the action button is now. desktop & mobile.

**Comment by marnovo** [comment]
Agreed with Ricardo so far.

**Comment by dpordomingo** [comment]
What I tried to explain is that there are two scenarios:

## On Error:
If an error occurs, the send button keeps being enabled, so the user can "retry" or modify the email sent. If we remove the send button, we lose both possibilities of "retrying" or modifying the email.
You can consider the following Sergio quote as examples:
> _an error on our side does not mean a permanent error. It can be caused by local connectivity problems or problems contacting the Slack API in that specific moment or even being in time after shutting down a docker image and getting up the new one_

When I wrote:
> _Before removing the send button we should ensure that re-sending the email has no sense at all with our current backend_

I meant that we should not remove the send button before ensuring that re-sending the email will not succeed in any case (as the ones described by Sergio, for example).
We could implement safe-nets that could reduce the utility of re-sending the email, but it should be analyzed as a different feature, in a different issue and pull-request.

## On Success:
Removing the submit button is feasible and I'll do so.

**Comment by dpordomingo** [comment]
@ricardobaeta the following screenshots shows the `onSuccess` state as agreed.
No changes in `initial` nor `onError` states.

## Hero form
### desktop


### iPhone 6 Plus
(no change due to resolution)

## Footer form
### desktop
image

### iPhone 6 Plus


/cc @marnovo

**Comment by ricardobaeta** [comment]
@dpordomingo So, as you explained, we have more than one error message because that can be: 

1) on our side
2) user connectivity
3) slack API.

Does it makes sense to have only one feedback message for three possible form errors?

**Comment by dpordomingo** [comment]
@marnovo @ricardobaeta I'd suggest to review the PR in terms of the [original user story](https://github.com/src-d/backlog/issues/967) (already overflowed, I know)
> "As a source{d} website user, I don't want to cringe when I see horrible icons in the Slack form so that I actually know that we had an error."

In case there is any other needed improvement, it should be done in a separated PR, and (imho) in a separated issue too.

**Comment by ricardobaeta** [comment]
> Because of that, we decided to have only one error message to suggest the user to contact us, and to leave the send button enabled in case the user wants to retry.

We could take a look at the copy then.

**Comment by marnovo** [comment]
LGTM. Approved

**Pull request merged**
