### PR TITLE
New Photos for Team Page

### PR DESCRIPTION
**Pull request by ricardobaeta**
Alex, Francesc, Javi and Rafa.

### CODE REVIEW

**Comment by dpordomingo** [comment]
If it is needed to create a new group for Francesc (it should be confirmed by @marnovo ) we would need a design or clear guidelines, so I'll be able to do it.

**Comment by ricardobaeta** [comment]
Francesc will be at the Management section :)

**Comment by dpordomingo** [comment]
Great!
Then, it is not needed a design, so you can edit the [hugo/data/team.yml](https://github.com/src-d/landing/blob/master/hugo/data/team.yml) on your own :dagger:

**Comment by ricardobaeta** [comment]
@dpordomingo 

https://github.com/src-d/landing/pull/222

**Comment by dpordomingo** [comment]
supersede by https://github.com/src-d/landing/pull/223

**Pull request closed without merging**
