### PR TITLE
Make the quotes random without modifying the dom

### PR DESCRIPTION
**Pull request by dpordomingo**
Lets avoid DOM operations :dancer: 
-- and solves https://github.com/src-d/landing/issues/25

It can be achieved assigning higher flex-order to random flex-items

### CODE REVIEW

**Comment by erizocosmico** [comment]
Is this more complex way worth not doing 2 simple DOM operations? If you guys think so then lgtm
On Wed, 14 Jun 2017 at 21:30, David <notifications@github.com<mailto:notifications@github.com>> wrote:

@dpordomingo<https://github.com/dpordomingo> requested your review on: src-d/landing#26<https://github.com/src-d/landing/pull/26> Make the quotes random without modifying the dom.

**Comment by erizocosmico** [comment]
ping @dpordomingo

**Comment by dpordomingo** [comment]
I don't like DOM operations when they're not really needed (and can be easily avoided); on the other side, working with flex order is not that tricky...
Anyway, you'd say how to proceed

**Comment by erizocosmico** [comment]
I think we can close this, since the modification of only adding the first 2 DOM nodes has already been merged.

**Pull request closed without merging**
