### PR TITLE
Fix low hanging fruits

### LINKED ISSUE #119: Low-hanging fruits suggestions
I think we could do some tiny adjustments to visual design. What do you think @marnovo @Serabe ?

## Landing Page

- [x] source{d} logo could be smaller (height: 30px; margin-top: 12px;)
- [x] Font-size on main navigation could be adjusted (a = font-size: 18px; margin-top: 0; ul = margin-top: 10px;)
- [x] Main heading could be bolder (font-weight: 600;)
- [x] Slack logo on Join the Community block could be smaller (height: 50px; margin-top: 22px;)
- [x] The project's slider control icons could be smaller (arrow = background-size: 20px 20px; dots = height: 10px; width: 10px;)
- [ ] On "what developers say" we could user two columns instead of two rows
- [x] On "join the community" block before the footer the slack logo could be smaller (height: 46px; margin-top: 40px;)

## Projects

- [x] There could be some more positive space bellow the main headings (margin-bottom: 28px;)

### PR DESCRIPTION
**Pull request by Serabe**
Fixes #119 except for the _what developers say_ section. The content does not fit two columns nicely so we need to think if we want to spend time on that or not.

2017-08-17 at 12 28
2017-08-17 at 12 28
2017-08-17 at 12 29
2017-08-17 at 12 29
2017-08-17 at 12 29
2017-08-17 at 12 29
2017-08-17 at 12 30

### CODE REVIEW

**Comment by ricardobaeta** [comment]
Other than this:

image

:shipit:

**Comment by Serabe** [comment]
That block was disappearing from there.

**Comment by Serabe** [comment]
@marnovo ping

**Comment by marnovo** [comment]
Much better, thanks guys!

**Pull request merged**
