### PR TITLE
New Enterprise page on the website

### PR DESCRIPTION
**Pull request by znegrin**
Hi @vcoisne,

Here is the Enterprise page referred to the issue [#1404](https://github.com/src-d/backlog/issues/1404) on the backlog: [Website revamp on communication & structure w/ new pages](https://github.com/src-d/backlog/issues/1404). It adds a new page for the Enterprise section. It can be checked at http://localhost:8081/enterprise/

Notice that the header navigation and the footer will be changed in a separate PR. It also will need some work on the form to make it work. Maybe @dpordomingo can help.

Here is a screenshot of the full page:

image

Please let me know if everything is ok.

Thank you!

### CODE REVIEW

**Comment by vcoisne** [comment]
Thank you @znegrin. 

Some minor edits: 

1. Please remove "access in minutes. No credit card required". We're still figuring out how the trial will work. 

2. Update title "Retrieval & Dependency Mapping" to "Automated Retrieval & Technology Mapping" and update the text under to "Automatically discover where your code is and map out your tech stacks both upstream and downstream so that you can asses, plan, execute and monitor your IT projects more effectively." 

3. Updated description for "Flexible deployment options" to "The simplicity of one-click deployment or the flexibility of managed on-premise, choose who takes care of running the platform while keeping full control of your data." 

4. Updated description for "Advanced queries and UDFs" to "The extensibility of the platform allows user to write custom user defined functions to extend their analysis beyond SQL queries."

**Comment by vcoisne** [comment]
One last thing sorry! The 4 use case title are as follow:

- IT Modernization & Application Portfolio Management

- DevOps & Cloud Native adoption

- Engineering effectiveness & efficiency 

- Talent Assessment and Management

**Comment by znegrin** [comment]
@vcoisne I updated the page. I guess it's only missing the proper form once it is prepared to be integrated. Thanks

**Comment by vcoisne** [comment]
Thank you @znegrin 

We're not able to edit the styles on the form itself, unfortunately. Either you can find a quick workaround to customize the look & feel of the form on the page or we remove that section altogether, for now, so that we can ship the page faster.

**Comment by znegrin** [comment]
> Thank you @znegrin
> 
> We're not able to edit the styles on the form itself, unfortunately. Either you can find a quick workaround to customize the look & feel of the form on the page or we remove that section altogether, for now, so that we can ship the page faster.

Hi @vcoisne,

It seems that it actually can be styled if it is a pardot form:
https://help.salesforce.com/articleView?id=pardot_forms_add_css_classes_to_fields.htm&type=5

If I can get access to that, I could fix it so quickly and finish the integration.

Thank you!

**Comment by vcoisne** [comment]
@znegrin sent you credentials via DM.

**Comment by znegrin** [comment]
Hi @vcoisne,

I just pushed a commit with the form integrated on the enterprise page.
I think it is now ready too.

**Comment by dpordomingo** [comment]
Changing the target branch to be `ee-candidate` instead of `master`

**Pull request merged**
