### PR TITLE
Content updates on the homepage

### PR DESCRIPTION
**Pull request by znegrin**
This PR is based on the requests added on the issue [#1404](https://github.com/src-d/backlog/issues/1404) in the backlog. It includes the following changes:

- Add play overlay button on top of the image below and link to 1m video https://www.youtube.com/watch?v=L8EuDaVnCIY&feature=youtu.be
- Add new use case images below to replace placeholders
- Add one sentence under the list of questions for each use case (not that the “learn more” Botton should always be aligned with the bottom of the images.
- Under “Any hosting environments” replace “Make better decisions based on actionable insights from graphs, charts and tables” by “You can host source{d} on any Public Cloud or behind your firewall”
- Remove the logo from under the quotes (per mockups)

image

### CODE REVIEW

**Comment by znegrin** [comment]
Hi @vcoisne,

I added the requested changes. Notice that the video overlay will stop on closing once this is merged with the get-started branch, as it includes the script for that.

Thank you!

**Comment by vcoisne** [comment]
Thank you @znegrin 

One last thing. can we update the title of the 1st solution to "Technical Debt Assessment & IT Modernization" on the homepage and Header + Enterprise page?

**Comment by znegrin** [comment]
Hi @vcoisne,

I changed the title to Technical Debt Assessment & IT Modernization on the homepage. Will add the other pages on their branches. Thank you!

image

**Comment by vcoisne** [comment]
Thank you @zuri 

Very sorry about the back and forth on terminology but after discussions with Eiso we decided on the following changes:

1. Update the tagline from "Accelerate your Digital Transformation by gaining visibility into your software portfolio, engineering team, and processes." to "Giving IT executives visibility into their software portfolio, engineering processes and workforce at scale"

2. Please updates the following solution titles: 

- From "Technical Debt Assessment & IT Modernization" to " IT Modernization & Compliance" 
- From "DevOps & Cloud Native adoption" to "DevOps & Cloud Native Transformation"
- From "Engineering effectiveness & efficiency" to "Engineering Effectiveness & Efficiency"
- From "Talent Assessment and Management" to "Talent Assessment & Management"

**Comment by znegrin** [comment]
Hi @vcoisne,

I uploaded the changes:

image

image

Thank you!

**Comment by dpordomingo** [comment]
Already in staging:
https://landing-staging.srcd.run

**Comment by vcoisne** [comment]
Changes look good. thank you. Final change: Pop up title should be updated from "1m Video" to "source{d}: The Data Platform for your Software Development Life Cycle"

Once I close the pop up the image and video play button overlay are gone 

Screen Shot 2019-06-25 at 10 13 03 AM

**Comment by znegrin** [comment]
> Changes look good. thank you. Final change: Pop up title should be updated from "1m Video" to "source{d}: The Data Platform for your Software Development Life Cycle"
> 
> Once I close the pop up the image and video play button overlay are gone
> 
> Screen Shot 2019-06-25 at 10 13 03 AM

On this branch it is working fine. Maybe is something related to the merge.

I updated the title and also added the new four images:

it-modernization
devops
engineering-effectiveness
talent-assessment

**Comment by vcoisne** [comment]
Awesome, thank you!!!

**Comment by dpordomingo** [comment]
Is this ready to be merged @vcoisne ?

**Pull request merged**
