### PR TITLE
Extract data team and os

### PR DESCRIPTION
**Pull request by dpordomingo**
depends on #319

The separation between data and templating was restored for `team` and `projects` sections; that way it will be way easier to keep those pages updated when adding, moving, sorting items.
- 700eccb Separate data and templating in OS projects
- 5346ff6 Separate data and templating in team

I used this PR to add @creachadair to the team!
https://github.com/src-d/landing/pull/321/files#diff-6bb0d9fa032c3676084edae453eea5edR63

And move Alex to LA team
https://github.com/src-d/landing/pull/321/files#diff-6bb0d9fa032c3676084edae453eea5edR66

### CODE REVIEW

**Comment by dpordomingo** [comment]
since there is no major changes, I'll auto merge this

**Comment by creachadair** [comment]
Looks (retroactively) good to me! 👍

**Comment by dpordomingo** [comment]
@creachadair 
You're now in our landing!!!
welcome on board :dancer: 

(it would be great if @marnovo brings his camera next week and fix this :wink:  )
image

**Comment by creachadair** [comment]
> [I]t would be great if @marnovo brings his camera next week and fix this 😉

It looks as if I'm not the only one missing!

**Comment by dpordomingo** [comment]
@meyskens and @vcoisne are also missing, but I'm afraid they're not coming to the office next week :(

**Comment by dpordomingo** [comment]
Maybe @marnovo forgot to add it?
You can also send it to me by email, and I'll do the rest.

**Pull request merged**
