### PR TITLE
Updating Company page as mentioned on #414 and #424

### LINKED ISSUE #414: Company page updates
@znegrin please make the following edits to the company page:

- Under roadmap replace “[…] as well as a single one through our powerful source{d} Engine and machine learning tools.” By  "[…] as well as a single one through our powerful source{d} platform and machine learning tools.”
- Remove all teams & photos, keep only Management section
- Remove “CAREERS, Job Opportunities Exceptional missions require exceptional people; we know that.If our challenges excite you and you want to help us to pave the future road towards machine learning on source code, check where you fit best from our current openings or drop us a message.”
- Remove “download engine” and “Newsletter” sections

### PR DESCRIPTION
**Pull request by znegrin**
fix #414

I updated the Company page according to the changes requested on #414 and mentioned on #424.

image

### CODE REVIEW

**Comment by dpordomingo** [comment]
Already at staging
https://landing-staging.srcd.run/company/#team

I'm not sure if the current `Team` heading is the better one for the current design, considering that it only appears management.
image

**Comment by vcoisne** [comment]
@dpordomingo @znegrin we should remove the "Team" title and text underneath and center the "Management" title instead.

**Comment by dpordomingo** [comment]
if we proceed that way I'd say that `Management` and its description should have the current style of `Team` and its description.

Something like this :point_down: 
image

**Comment by estherrgarcia** [comment]
I don't know why we are doing that but in my opinion, is against our culture. The team section is an easy way to show we are multicultural and open to hiring people anywhere (more or less).

**Comment by znegrin** [comment]
I updated this page:

image

**Comment by znegrin** [comment]
I also removed the buttons on the top header for consistency with the other pages and also because there is no Team section anymore.

image

**Pull request merged**
