### PR TITLE
embedded newsletter sign up form in the footer. Fixed #263

### LINKED ISSUE #263: Embed newsletter sign up form in the footer
I think we'd have higher conversation rate if we embed the sign up form on the website itself (in the footer) vs pointing people to an external landing page. 

Here is the embed code:

`<iframe src="http://go.sourced.tech/l/578561/2018-08-17/397lv" width="100%" height="500" type="text/html" frameborder="0" allowTransparency="true" style="border: 0"></iframe>` #

### PR DESCRIPTION
**Pull request by ConnorBrereton**

### CODE REVIEW

**Comment by ConnorBrereton** [comment]
did the pull request help out?

**Comment by carlosms** [comment]
I don't mean to be rude, but I have to be honest. Proposing a visual change without being able to check how it looks is not ideal to say the least.
This PR adds a form without any context what it is about in the footer. Plus a huge whitespace block.
image

By the way. In order to link to another issue with a keyword, you need to use it in the description or the commit message. Not the PR title. See the reference here: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by ConnorBrereton** [comment]
@carlosms I don't mean to be rude either but I was literally told at Hacktoberfest that if setting up the Go environment per the documentation didn't work (which it hasn't for myself and others) it is ok to go forward and do this PR so long as I communicate that it was not tested locally. My apologies for following through with the instructions that were given to me.

**Comment by dpordomingo** [comment]
Thank you for taking your time to help us with this, but we can not merge features with no design

**Comment by dpordomingo** [comment]
(we should also apologize for proposing a change but not providing better specs :bowing_man: )

**Pull request closed without merging**
