### PR TITLE
Add content 2nd draft

### PR DESCRIPTION
**Pull request by marnovo**
Signed-off-by: Marcelo Novaes <mnovaes@gmail.com>

Second draft of the landing content, now containing all sections and fields.

### CODE REVIEW

**Comment by marnovo** [comment]
@eiso @mcuadros please review the new content draft. I have set up a ngrok server to make it easier to review content in-situ at: http://68ce707d.ngrok.io
keep in mind you won't be able to access documentation and custom subdomains from this URL, but it matters not for this content review.

@dpordomingo please special focus on the `categories.yml` just to make sure URLs, subdomains and are according to your agreements with infra. I tried to minimize conflicts as well as I could.

**Comment by dpordomingo** [comment]
Are we keeping the old manifesto?

I saw a could of broken links; it happened because you worked with an old version of the repo; I'll fix it in your bran

**Comment by dpordomingo** [comment]
Are we keeping the old manifesto?

I saw a could of broken links; it happened because you worked with an old version of the repo; I'll fix it in your branhi and I'll ping you

There are no blog posts nor opened positions because it for an work well with ngrock

**Comment by marnovo** [comment]
@dpordomingo 

>Are we keeping the old manifesto?

So far, yes; @eiso can confirm that.

> I saw a couple of broken links; it happened because you worked with an old version of the repo; I'll fix it in your branch and I'll ping you

Thanks, please do.

> There are no blog posts nor opened positions because it for an work well with ngrock

Well it actually works here (posts show up and positions as well).

P.s.: Eiso reviewed the content and gave some feedback on the product channel, so after you fix my branch I'll make these changes.

**Comment by marnovo** [comment]
> working in your branch...

@dpordomingo let me know when it's done and I can make further changes (and any caveats just so that I don't screw things up).

> Typeform for requesting a demo is private

Thanks, it was not clear from their configurations, fixed it and it's now public.

**Comment by dpordomingo** [comment]
ready at staging
https://landing-staging.srcd.run/

**Pull request merged**
