### PR TITLE
Add content 3rd draft

### PR DESCRIPTION
**Pull request by marnovo**
Signed-off-by: Marcelo Novaes <mnovaes@gmail.com>

- Content draft v3:
  - Capitalized the beginning of full text blocks;
  - Updated source{d} API example + desc (now allows HTML);
  - Changed roadmap last paragraph;

### CODE REVIEW

**Comment by marnovo** [comment]
@dpordomingo @eiso FYI;

**Comment by dpordomingo** [comment]
nope, `ngrok` does not work with landing -> no styles and many other problems.
It could be a feature request, but it should be planned in advance, sorry.
At this moment, the validation can be only done at Staging, after merging this PR.

The best alternative for me would be to automatically deploy to staging when pushed against staging branch, instead of master. That way it could be validated at staging without merging the PR.
--> I will consider that point with @src-d/infrastructure folks, because the current workflow was defined by Sergio, so it would be needed a small change to work in the way I'm proposing.

**Comment by marnovo** [comment]
> @marnovo if you want to deploy this into staging (to let the ppl to validate it) just tell me, and I'll merge -> deploy to Staging (as we did with your prev PR)

Please do! @dpordomingo 
Thank you.

**Comment by dpordomingo** [comment]
deployed and ready at staging
https://landing-staging.srcd.run

**Pull request merged**
