### PR TITLE
Implement 'head out-of-the-box' feature

### PR DESCRIPTION
**Pull request by dpordomingo**
improves https://github.com/src-d/backlog/issues/842

To achieve the  'head out-of-the-box' feature it is needed:
- all pictures with transparent background (already provided)
- all heads should be at the same position (not yet)

If heads are not at the very same position, that differences will be quite clear due to the circle behind the head, that acts as a "measurement guide"

@marnovo could you review **all** images to ensure that all heads are at the very same position?
I'd sugest to use "as a guide" the [static/img/people/placeholder/new-man.png](https://github.com/src-d/landing/blob/master/static/img/people/placeholder/new-man.png) image, and use it too for the new guys pictures in the future.
Otherwise the page will look like in the image under these lines

team-out-of-the-box

### CODE REVIEW

**Comment by marnovo** [comment]
Looking good. @dpordomingo I think leveling by using the second row (Sonia/Alfredo/Juanjo/Manuel) is truer to the original design, thus the "new man/woman" and other pictures could also follow these as the rule.

**Comment by dpordomingo** [comment]
@marnovo There are 2 different issues:
- **to show all heads at the same height** -> it will be fixed providing all the images with the head in the same position; it does not matter if you choose to be a guide: the Sonia's one (highest), or the Máximo's one (lowest); you can choose whatever one to be your guide.
- **to stablish the "offset" of the head** -> the design says `-20px`, but it can be whatever you want (it is done by css), so once the images have been provided, the `position-top` is fixed to a certain quantity according to the design or any other (that's because the guide you use to fix the images, does not matter at all regarding to the final view).

**Comment by Serabe** [comment]
I guess we can merge this PR and then discuss modifications once all pictures are normalized. Do you agree @marnovo and @dpordomingo ?

**Comment by dpordomingo** [comment]
I agree, of course :D

**Comment by marnovo** [comment]
@Serabe Agreed!

**Pull request merged**
