### PR TITLE
remove references to gutter-size and column-size in variables

### PR DESCRIPTION
**Pull request by erizocosmico**
If we're going percentages we might want this before such event takes place

### CODE REVIEW

**Comment by erizocosmico** [comment]
It was gonna be percentage-based. Now I think the gutter won't be. We'll see what happens when the new grid is PR'd.

**Comment by dpordomingo** [comment]
Now I understand your pov, but if the `$gutter-size` is changed by a `whatever%`, the `30px` dimmensions keeps being relevant somehow... then it would be maybe useful to rename the variable to any other name (because in that scenario it will no longer be the "gutter size", but the "general-modulus" or any other fancier name)

**Comment by erizocosmico** [comment]
Anyway, we'll wait til the PR of the grid is done

**Comment by Serabe** [comment]
`$gutter-size` is px based. For more info see today's _su_ or wait for the new grid landing.

**Comment by dpordomingo** [comment]
plz, ping us once this PR is ready to review again :D

**Pull request closed without merging**
