### PR TITLE
Content updates on Enterprise page

### PR DESCRIPTION
**Pull request by znegrin**
This PR is based on the requests added on the issue [#1404](https://github.com/src-d/backlog/issues/1404) in the backlog. It includes the following changes:

- Add the following paragraph under the “Start Your source{d} Enterprise Hosted Trial” title: " Whether you’re an executives looking to review a dashboard with Engineering KPIs or an IT managers querying the data yourself to inform your decisions, our built in dashboard solution abstracts away the complexity of analyzing your SDLC at scale so that you can focus on your business outcomes."
- Center the icons in the “What do you get with source{d} Enterprise?” Section
- Replace the placeholder images with the same one that the homepage

image

### CODE REVIEW

**Comment by dpordomingo** [comment]
@vcoisne I realized that "download source{d}" call to action buttons open the old "https://sourced.tech/engine/" page, what seems to be incorrect. Imo they should open "https://go.sourced.tech/engine-download", or similar. wdyt?

image

**Comment by znegrin** [comment]
Hi @vcoisne,

I switched the images as requested. I also changed the links as suggested by @dpordomingo.

image

Please let me know if there are additional changes.

Thank you!

**Comment by znegrin** [comment]
I updated the title of the IT Modernization section as requested on #409 

image

**Comment by vcoisne** [comment]
Per comment latest comment on https://github.com/src-d/landing/pull/409 - Please updates the following solution titles: 

- From "Technical Debt Assessment & IT Modernization" to " IT Modernization & Compliance" 
- From "DevOps & Cloud Native adoption" to "DevOps & Cloud Native Transformation"
- From "Engineering effectiveness & efficiency" to "Engineering Effectiveness & Efficiency"
- From "Talent Assessment and Management" to "Talent Assessment & Management"

**Comment by znegrin** [comment]
Hi @vcoisne,

I uploaded all the requested changes. I just would need to be sure about the structure and links of the solution pages, as right now I just added some placeholders but I don't know if those are ok or you had others in mind.

image

Thank you!

**Comment by dpordomingo** [comment]
Already in staging:
https://landing-staging.srcd.run/enterprise/

**disclaimer**
I had some conflicts merging this branch into staging, so just confirm @znegrin that everything is as expected

**Comment by znegrin** [comment]
> Already in staging:
> https://landing-staging.srcd.run/enterprise/
> 
> **disclaimer**
> I had some conflicts merging this branch into staging, so just confirm @znegrin that everything is as expected

@dpordomingo  It seems that the css are not ok, as it is still showing a curve on top of the first section and it shouldn't be there.

**Comment by vcoisne** [comment]
@znegrin thank you, changes look good. The URLs should be as follow once the solution pages are live. 

sourced.tech/solutions/it-modernization-and-compliance
sourced.tech/solutions/devops-cloud-native-transformation
sourced.tech/solutions/engineering-effectiveness-efficiency
sourced.tech/solutions/talent-assesment-and-management

Anchor link should be as follow:

sourced.tech/enterprise-edition-demo-request

**Comment by znegrin** [comment]
> @znegrin thank you, changes look good. The URLs should be as follow once the solution pages are live.
> 
> https://sourced.tech/solutions/it-modernization-and-compliance
> https://sourced.tech/solutions/devops-cloud-native-transformation
> https://sourced.tech/solutions/engineering-effectiveness-efficiency
> https://sourced.tech/solutions/talent-assesment-and-management
> 
> Anchor link should be as follow:
> 
> sourced.tech/enterprise-edition-demo-request

I just uploaded an update with the proper links. Also all the pages are now as PRs individually:
#420, #421, #422 and #423

**Comment by znegrin** [comment]
As requested on #405 I updated the page to source{d} Enterprise Edition ([products/enterprise-edition](https://sourced.tech/product/enterprise-edition))

**Comment by dpordomingo** [comment]
Already at staging.
https://landing-staging.srcd.run/products/enterprise-edition/

But I detected a weird thing:
>The header and the wave background does not match.
image

We haven't this layout in any of our pages, so I'd drop also this wave, so it would be:
image

should we merge with this issue @vcoisne ?

**Comment by znegrin** [comment]
> Already at staging.
> https://landing-staging.srcd.run/products/enterprise-edition/
> 
> But I detected a weird thing:
> 
> > The header and the wave background does not match.
> > image
> 
> We haven't this layout in any of our pages, so I'd drop also this wave, so it would be:
> image
> 
> should we merge with this issue @vcoisne ?

The wave shouldn't be there. It was related to the merge, I think I commented this already ;) Thank you!

**Comment by dpordomingo** [comment]
Yes. Maybe. But if it's happening in `staging` it will also happen in `master` once everything is there.
Let me know when it should be solved, and I'll deploy it over `staging` to perform a final sanity check before merging.

**Comment by znegrin** [comment]
> Yes. Maybe. But if it's happening in `staging` it will also happen in `master` once everything is there.
> Let me know when it should be solved, and I'll deploy it over `staging` to perform a final sanity check before merging.

I don't know how to fix that here.
 
It is just a line of css that I removed from this branch and seems to be added from the other branches. Also I am trying to fix the merge conflict but in this case I merged `revamp-candidate` and nothing happened. I think it is related to the removed file: `hugo/layouts/enterprise/single.html`.

**Comment by dpordomingo** [comment]
I think that `src-d:revamp-candidate`, for example, will show you the conflicts, and most probably once they're solved, the extra wave issues will be also solved.

**Comment by znegrin** [comment]
> I think that `src-d:revamp-candidate`, for example, will show you the conflicts, and most probably once they're solved, the extra wave issues will be also solved.

If I merge `src-d:revamp-candidate` into this one, no conflicts are shown.

**Comment by dpordomingo** [comment]
> If I merge `src-d:revamp-candidate` into this one, no conflicts are shown.

It does not seem to be possible.
GitHub says so :point_down: 

image

**Comment by znegrin** [comment]
Now it seems that the conflicts are fixed. I also fixed the links and the top curve, and replaced the images for the new ones.

image

**Pull request merged**
